#Default Configuration File
communalbounty:
    enable: true
    increment: 5
    decrement: 5
    bountydecreaseonkill: false
psbounty:
    enable: true
    min: 0
    max: 200
showvictimmessages: true
showkillermessages: true
needbountylicense: false
forcegoldecon: false 
MySQL: 
    enabled: false 
    host: ''
    port: ''
    database: '' 
    username: ''
    password: ''